# Generated by Django 3.2 on 2021-12-29 18:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=90, unique=True)),
                ('course_desc', models.TextField()),
                ('course_subj', models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], max_length=20)),
                ('course_thumbnail', models.ImageField(default='default_course.jpeg', upload_to='Course_Thumbnail', validators=[django.core.validators.validate_image_file_extension])),
                ('course_published_on', models.DateTimeField(auto_now_add=True)),
                ('course_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True)),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], max_length=50)),
                ('desc', models.TextField(blank=True, default='No desc')),
                ('thumbnail', models.ImageField(default='default_notes.jpeg', upload_to='thumbnail_notes', validators=[django.core.validators.validate_image_file_extension])),
                ('file', models.FileField(upload_to='Notes', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])])),
                ('published_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid_title', models.CharField(max_length=60, unique=True)),
                ('vid_desc', models.TextField(blank=True, default='no desc')),
                ('vid_thumbnail', models.ImageField(default='default_video.png', upload_to='thumbnail_video', validators=[django.core.validators.validate_image_file_extension])),
                ('vid_video', models.FileField(upload_to='Videos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV', 'WMV', 'AVI', 'AVCHD', 'FLV', 'F4V', 'SWF', 'MKV'])])),
                ('vid_published_on', models.DateTimeField(auto_now_add=True)),
                ('vid_views', models.IntegerField(default=0)),
                ('vid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vid_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_vid_message', models.CharField(max_length=100)),
                ('comment_vid_commented_on', models.DateTimeField(auto_now_add=True)),
                ('comment_vid_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.video')),
            ],
        ),
        migrations.CreateModel(
            name='NotesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=100)),
                ('commented_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.notes')),
            ],
        ),
    ]
