# Generated by Django 3.2 on 2022-01-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='vid_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='vid_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_subj',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Physics', 'Physics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Chemistry', 'Chemistry'), ('Maths', 'Maths'), ('Physics', 'Physics')], max_length=50),
        ),
    ]
