# Generated by Django 3.2 on 2022-01-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20220106_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_subj',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry')], max_length=50),
        ),
    ]
