# Generated by Django 3.2 on 2022-01-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20220108_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subj',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Maths', 'Maths')], max_length=50),
        ),
    ]
