# Generated by Django 3.2 on 2022-01-09 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20220109_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subj',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Physics', 'Physics')], max_length=50),
        ),
    ]
