# Generated by Django 3.2 on 2022-01-21 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20220110_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_subj',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='subject',
            field=models.CharField(choices=[('Physics', 'Physics'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry')], max_length=50),
        ),
    ]
